****2 NODE RAC TO SINGLE INSTANCE DATA GUARD CONFIGURATION***

Switchover steps in below link :

Switchover step by step

1)*************Pre_Info**************


set pages 9999 lines 300
col OPEN_MODE for a10
col HOST_NAME for a30
select name DB_NAME,HOST_NAME,DATABASE_ROLE,OPEN_MODE,log_mode,version DB_VERSION,LOGINS,to_char(STARTUP_TIME,'DD-MON-YYYY HH24:MI:SS') "DB UP TIME" from v$database,v$instance;

   INST_ID INSTANCE_NAME    DB_NAME   HOST_NAME                      DATABASE_ROLE    LOG_MODE     OPEN_MODE  DB_VERSION        LOGINS     DB UP TIME
---------- ---------------- --------- ------------------------------ ---------------- ------------ ---------- ----------------- ---------- --------------------
         1 Findb1           FINDB     dm01db01.database.com          PRIMARY          ARCHIVELOG   READ WRITE 12.1.0.1.0        ALLOWED    26-APR-2020 16:41:40
         2 Findb2           FINDB     dm01db02.database.com          PRIMARY          ARCHIVELOG   READ WRITE 12.1.0.1.0        ALLOWED    26-APR-2020 16:41:22


SQL> show pdbs

    CON_ID CON_NAME     OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 FINPDB                            READ WRITE NO
SQL>
SQL> alter database force logging;

Database altered.

SQL> select force_logging from v$database;

FORCE_LOGGING
---------------------------------------
YES

SQL> select GROUP#,THREAD#,BYTES from v$log;

    GROUP#    THREAD#      BYTES
---------- ---------- ----------
         1          1   52428800
         2          1   52428800
         3          2   52428800
         4          2   52428800

SQL> select member from v$logfile;

MEMBER
-------------------------------------------------------
+DATA/FINDB/ONLINELOG/group_2.263.1038428391
+FRA/FINDB/ONLINELOG/group_2.258.1038428393
+DATA/FINDB/ONLINELOG/group_1.262.1038428389
+FRA/FINDB/ONLINELOG/group_1.257.1038428391
+DATA/FINDB/ONLINELOG/group_3.269.1038428699
+FRA/FINDB/ONLINELOG/group_3.259.1038428719
+DATA/FINDB/ONLINELOG/group_4.270.1038428721
+FRA/FINDB/ONLINELOG/group_4.260.1038428723

8 rows selected.


SQL> show parameter db_name

NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
db_name                              string      Findb
SQL>
SQL>
SQL> show parameter db_unique_name

NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
db_unique_name                       string      Findb


2)***PARAMETERS TO BE SET AT PRIMARY DATABASE***

--alter system set log_archive_config='DG_CONFIG=(Findb,Findr)' SCOPE=both sid='*';

-- alter system set db_unique_name=Findb;

-- alter system set fal_server=Findr SCOPE=both sid='*';   (----unique name of  second DR machine)

-- alter system set fal_client=Findb SCOPE=both sid='*';   (----unique name of  Primary machine)

--alter system set log_archive_dest_1='LOCATION=+FRA' SCOPE=both sid='*';

--ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=Findr NOAFFIRM ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=Findr' SCOPE=both sid='*';

--alter system set log_archive_dest_state_1=enable SCOPE=both sid='*';

--alter system set log_archive_dest_state_2=enable SCOPE=both sid='*';

--alter system set standby_file_management=auto SCOPE=both sid='*';


3)*****Tnsfile entry for Primary and DR******

Tnsfile entry for Primary and DR :

Findr =
   (DESCRIPTION =
     (ADDRESS_LIST =
       (ADDRESS = (PROTOCOL = TCP)(HOST = dm01dr01.database.com)(PORT = 1521))
     )
     (CONNECT_DATA =
       (SERVER = DEDICATED)
       (SERVICE_NAME = Findr.database.com)
    (UR = A)
     )
   )


Findb =
   (DESCRIPTION =
     (ADDRESS_LIST =
       (ADDRESS = (PROTOCOL = TCP)(HOST = dm01scan.database.com)(PORT = 1521))
     )
     (CONNECT_DATA =
       (SERVER = DEDICATED)
       (SERVICE_NAME = Findb.database.com)
    (UR = A)
     )
   )



4)*****Listener file entry For Primary and DR*****

Primary Database example for Listener.ora

[grid@dm01db01 admin]$ cat listener.ora
# listener.ora Network Configuration File: /oracle/app/grid/gr_home/network/admin/listener.ora
# Generated by Oracle configuration tools.

ENABLE_GLOBAL_DYNAMIC_ENDPOINT_LISTENER_SCAN2 = ON

ENABLE_GLOBAL_DYNAMIC_ENDPOINT_LISTENER_SCAN1 = ON

VALID_NODE_CHECKING_REGISTRATION_MGMTLSNR = SUBNET

VALID_NODE_CHECKING_REGISTRATION_LISTENER_SCAN2 = OFF

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = Findb.database.com)
      (ORACLE_HOME = /oracle/app/orawork/product/12.1.0.2/db_1)
      (SID_NAME = Findb)
    )
    (SID_DESC =
      (GLOBAL_DBNAME = Findr.database.com)
      (ORACLE_HOME = /oracle/app/orawork/product/12.1.0.2/db_1)
      (SID_NAME = Findr)
    )
  )

VALID_NODE_CHECKING_REGISTRATION_LISTENER_SCAN1 = OFF

VALID_NODE_CHECKING_REGISTRATION_LISTENER = SUBNET

MGMTLSNR =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = IPC)(KEY = MGMTLSNR))
  )

ADR_BASE_MGMTLSNR = /oracle/app/grid/gr_base

SID_LIST_LISTENER_SCAN2 =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = Findb)
      (ORACLE_HOME = /oracle/app/orawork/product/12.1.0.2/db_1)
      (SID_NAME = Findb)
    )
    (SID_DESC =
      (GLOBAL_DBNAME = Findr)
      (ORACLE_HOME = /oracle/app/orawork/product/12.1.0.2/db_1)
      (SID_NAME = Findr)
    )
  )

SID_LIST_LISTENER_SCAN1 =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = Findb)
      (ORACLE_HOME = /oracle/app/orawork/product/12.1.0.2/db_1)
      (SID_NAME = Findb)
    )
    (SID_DESC =
      (GLOBAL_DBNAME = Findr)
      (ORACLE_HOME = /oracle/app/orawork/product/12.1.0.2/db_1)
      (SID_NAME = Findr)
    )
  )

ENABLE_GLOBAL_DYNAMIC_ENDPOINT_MGMTLSNR = ON

LISTENER =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = IPC)(KEY = LISTENER))
  )

ADR_BASE_LISTENER = /oracle/app/grid/gr_base

ENABLE_GLOBAL_DYNAMIC_ENDPOINT_LISTENER = ON

LISTENER_SCAN2 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = IPC)(KEY = LISTENER_SCAN2))
  )

LISTENER_SCAN1 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = IPC)(KEY = LISTENER_SCAN1))
  )

ADR_BASE_LISTENER_SCAN2 = /oracle/app/grid/gr_base

ADR_BASE_LISTENER_SCAN1 = /oracle/app/grid/gr_base


Standby Database example for listener.ora

[grid@dm01dr01 admin]$ cat listener.ora
# listener.ora Network Configuration File: /oracle/app/grid/gr_home/network/admin/listener.ora
# Generated by Oracle configuration tools.

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = Findb.database.com)
      (ORACLE_HOME = /oracle/app/orawork/product/12.1.0.2/db_1)
      (SID_NAME = Findb)
    )
    (SID_DESC =
      (GLOBAL_DBNAME = Findr.database.com)
      (ORACLE_HOME = /oracle/app/orawork/product/12.1.0.2/db_1)
      (SID_NAME = Findr)
    )
  )

VALID_NODE_CHECKING_REGISTRATION_LISTENER = SUBNET

LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = dm01dr01.database.com)(PORT = 1521))
    )
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

ADR_BASE_LISTENER = /oracle/app/grid

ENABLE_GLOBAL_DYNAMIC_ENDPOINT_LISTENER = ON


4.1)*****Tnsping output after listener and tnsfile config********

Prod

[oracle@dm01db02 admin]$ tnsping findb

TNS Ping Utility for Linux: Version 12.1.0.1.0 - Production on 26-APR-2020 23:54:02

Copyright (c) 1997, 2013, Oracle.  All rights reserved.

Used parameter files:


Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = dm01scan.database.com)(PORT = 1521))) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = Findb.database.com) (UR = A)))
OK (0 msec)
[oracle@dm01db02 admin]$
[oracle@dm01db02 admin]$ tnsping findr

TNS Ping Utility for Linux: Version 12.1.0.1.0 - Production on 26-APR-2020 23:54:05

Copyright (c) 1997, 2013, Oracle.  All rights reserved.

Used parameter files:


Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = dm01dr01.database.com)(PORT = 1521))) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = Findr.database.com) (UR = A)))
OK (10 msec)



DR : 

[oracle@dm01dr01 dbs]$ tnsping findb

TNS Ping Utility for Linux: Version 12.1.0.1.0 - Production on 26-APR-2020 23:53:17

Copyright (c) 1997, 2013, Oracle.  All rights reserved.

Used parameter files:


Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = dm01scan.database.com)(PORT = 1521))) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = Findb.database.com) (UR = A)))
OK (0 msec)

[oracle@dm01dr01 dbs]$
[oracle@dm01dr01 dbs]$
[oracle@dm01dr01 dbs]$ tnsping findr

TNS Ping Utility for Linux: Version 12.1.0.1.0 - Production on 26-APR-2020 23:53:23

Copyright (c) 1997, 2013, Oracle.  All rights reserved.

Used parameter files:


Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = dm01dr01.database.com)(PORT = 1521))) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = Findr.database.com) (UR = A)))
OK (0 msec)


4.2)*******Primary Database Pfile********

Findb2.__data_transfer_cache_size=0
Findb1.__data_transfer_cache_size=0
Findb1.__db_cache_size=268435456
Findb2.__db_cache_size=285212672
Findb2.__java_pool_size=16777216
Findb1.__java_pool_size=16777216
Findb1.__large_pool_size=33554432
Findb2.__large_pool_size=33554432
Findb1.__oracle_base='/oracle/app/orawork'#ORACLE_BASE set from environment
Findb2.__oracle_base='/oracle/app/orawork'#ORACLE_BASE set from environment
Findb2.__pga_aggregate_target=385875968
Findb1.__pga_aggregate_target=385875968
Findb2.__sga_target=754974720
Findb1.__sga_target=754974720
Findb1.__shared_io_pool_size=33554432
Findb2.__shared_io_pool_size=33554432
Findb1.__shared_pool_size=385875968
Findb2.__shared_pool_size=369098752
Findb2.__streams_pool_size=0
Findb1.__streams_pool_size=0
*.audit_file_dest='/oracle/app/orawork/admin/Findr/adump'
*.audit_trail='db'
*.cluster_database=true
*.compatible='12.1.0.0.0'
*.control_files='+DATA/FINDB/CONTROLFILE/current.261.1038428387','+FRA/FINDB/CONTROLFILE/current.256.1038428387'
*.db_block_size=8192
*.db_create_file_dest='+DATA'
*.db_domain='database.com'
*.db_name='Findb'
*.db_recovery_file_dest='+FRA'
*.db_recovery_file_dest_size=9000m
*.diagnostic_dest='/oracle/app/orawork'
*.dispatchers='(PROTOCOL=TCP) (SERVICE=FindbXDB)'
*.enable_pluggable_database=true
*.fal_client='FINDB'
*.fal_server='FINDR'
Findb2.instance_number=2
Findb1.instance_number=1
*.log_archive_config='DG_CONFIG=(Findb,Findr)'
*.log_archive_dest_1='LOCATION=+FRA'
*.log_archive_dest_2='SERVICE=Findr NOAFFIRM ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=Findr'
*.log_archive_dest_state_1='ENABLE'
*.log_archive_dest_state_2='ENABLE'
*.log_archive_format='%t_%s_%r.arc'
*.memory_target=1080m
*.open_cursors=300
*.processes=500
*.remote_login_passwordfile='exclusive'
*.sessions=555
*.standby_file_management='AUTO'
Findb2.thread=2
Findb1.thread=1
Findb2.undo_tablespace='UNDOTBS2'
Findb1.undo_tablespace='UNDOTBS1'


4.3)*********Standby Database pfile*********

*.audit_file_dest='/oracle/app/orawork/admin/Findr/adump'
*.audit_trail='db'
*.compatible='12.1.0.0.0'
*.db_block_size=8192
*.db_create_file_dest='+DATA'
*.db_domain='database.com'
*.instance_name=Findr
*.db_name='Findb'
*.db_unique_name='Findr'
*.db_recovery_file_dest='+FRA'
*.db_recovery_file_dest_size=9000m
*.diagnostic_dest='/oracle/app/orawork'
*.dispatchers='(PROTOCOL=TCP) (SERVICE=FindrXDB)'
*.enable_pluggable_database=true
*.fal_client='FINDR'
*.fal_server='FINDB'
*.log_archive_config='DG_CONFIG=(Findr,Findb)'
*.log_archive_dest_1='LOCATION=+FRA'
*.log_archive_dest_2='SERVICE=Findb NOAFFIRM ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=Findb'
*.log_archive_dest_state_1='ENABLE'
*.log_archive_dest_state_2='ENABLE'
*.log_archive_format='%t_%s_%r.arc'
*.memory_target=1080m
*.open_cursors=300
*.processes=500
*.remote_login_passwordfile='exclusive'
*.sessions=555
*.standby_file_management='AUTO'
*.enable_pluggable_database=true


5)*******ON STANDBY DATABASE******

--FIRST MAKE A SERVICE

--export ORACLE_SID=Findr

--export ORACLE_HOME=/oracle/app/orawork/product/12.1.0.2/db_1

--alter system set fal_server=Findb

--alter system set fal_client=Findr

--ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=Findb NOAFFIRM ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=Findb' SCOPE=both sid='*';

--alter system set log_archive_dest_1='LOCATION=+FRA' scope=both;

--alter system set db_unique_name=Findr

6)*******Startup Standby database to nomount********


mount -t tmpfs shmfs -o size=2G /dev/shm

[oracle@dm01dr01 dbs]$ export ORACLE_SID=Findr
[oracle@dm01dr01 dbs]$ sqlplus / as sysdba

SQL*Plus: Release 12.1.0.1.0 Production on Sun Apr 26 20:52:31 2020

Copyright (c) 1982, 2013, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> startup nomount
ORACLE instance started.

Total System Global Area 1135747072 bytes
Fixed Size                  2287528 bytes
Variable Size             905971800 bytes
Database Buffers          218103808 bytes
Redo Buffers                9383936 bytes


7)*******Connect primary Rman with below command auxillary standby******

[oracle@dm01dr01 dbs]$ rman target sys/Password1@Findb auxiliary sys/Password1@Findr

Recovery Manager: Release 12.1.0.1.0 - Production on Sun Apr 26 23:52:21 2020

Copyright (c) 1982, 2013, Oracle and/or its affiliates.  All rights reserved.

connected to target database: FINDB (DBID=764828770)
connected to auxiliary database: FINDB (not mounted)

Exit


[oracle@dm01dr01 orawork]$ cat restore_RACDG.sh
export ORACLE_SID=Findr
export ORACLE_HOME=/oracle/app/orawork/product/12.1.0.2/db_1
export PATH=$ORACLE_HOME/bin:$PATH
export NLS_DATE_FORMAT='YYYY-MM-DD:hh24:mi:ss'
date
echo "Begin restore"
rman target sys/Password1@Findb auxiliary sys/Password1@Findr
cmdfile=/oracle/app/orawork/restore_Racdg.rcv
log=/oracle/app/orawork/restore_Racdg.log
date
echo "End restore"

[oracle@dm01dr01 orawork]$ cat restore_RACDG.rcv
run
{
ALLOCATE CHANNEL CHNL1 DEVICE TYPE disk;
ALLOCATE CHANNEL CHNL2 DEVICE TYPE disk;
ALLOCATE AUXILIARY CHANNEL CHNL3 DEVICE TYPE disk;
ALLOCATE AUXILIARY CHANNEL CHNL4 DEVICE TYPE disk;
duplicate target database for standby from active database;
RELEASE CHANNEL CHNL1;
RELEASE CHANNEL CHNL2;
RELEASE CHANNEL CHNL3;
RELEASE CHANNEL CHNL4;
}

8) ************LOG FILE*******************

[oracle@dm01dr01 app]$ rman target sys/Password1@Findb auxiliary sys/Password1@Findr

Recovery Manager: Release 12.1.0.1.0 - Production on Mon Apr 27 23:21:33 2020

Copyright (c) 1982, 2013, Oracle and/or its affiliates.  All rights reserved.

connected to target database: FINDB (DBID=764828770)
connected to auxiliary database: FINDB (not mounted)






Alter database recover managed standby database disconnect from session;

SQL> select process,status,sequence# from gv$managed_standby;


SELECT ARCH.THREAD# "Thread", ARCH.SEQUENCE# "Last Sequence Received", APPL.SEQUENCE# "Last Sequence Applied", (ARCH.SEQUENCE# - APPL.SEQUENCE#) "Difference" FROM (SELECT THREAD# ,SEQUENCE# FROM V$ARCHIVED_LOG WHERE (THREAD#,FIRST_TIME ) IN (SELECT THREAD#,MAX(FIRST_TIME) FROM V$ARCHIVED_LOG GROUP BY THREAD#)) ARCH,(SELECT THREAD# ,SEQUENCE# FROM V$LOG_HISTORY WHERE (THREAD#,FIRST_TIME ) IN (SELECT THREAD#,MAX(FIRST_TIME) FROM V$LOG_HISTORY GROUP BY THREAD#)) APPL WHERE ARCH.THREAD# = APPL.THREAD# ORDER BY 1;



https://www.sultandba.com/2020/05/creating-single-instance-physical.html



==
https://logic.edchen.org/how-to-build-asymmetric-standby-database-for-data-guard/



==
https://community.oracle.com/tech/developers/discussion/4417532/tech-article-five-steps-for-installing-oracle-database-12c-on-oracle-solaris-11


==https://ibrisim.wordpress.com/2017/02/03/oracle-12-1-0-2-installation-on-solaris-11-sparc/


archivo.rsp
oracle.install.option=INSTALL_DB_SWONLY
 UNIX_GROUP_NAME=oinstall
 INVENTORY_LOCATION=/u01/app/oraInventory
 ORACLE_HOME=/u01/app/oracle/product/12.2.0.1/dbhome_1
 ORACLE_BASE=/u01/app/oracle
 oracle.install.db.InstallEdition=EE
 oracle.install.db.OSDBA_GROUP=dba
 oracle.install.db.OSOPER_GROUP=dba
 oracle.install.db.OSBACKUPDBA_GROUP=dba
 oracle.install.db.OSDGDBA_GROUP=dba
 oracle.install.db.OSKMDBA_GROUP=dba
 oracle.install.db.OSRACDBA_GROUP=dba
 oracle.install.db.OSRACDBA_GROUP=dba
 SECURITY_UPDATES_VIA_MYORACLESUPPORT=false
 DECLINE_SECURITY_UPDATES=true


===OR
./runInstaller -ignoreSysPrereqs -ignorePrereq -waitforcompletion -showProgress -silent \
    -responseFile /tmp/database/response/db_install.rsp \
    oracle.install.option=INSTALL_DB_SWONLY \
    ORACLE_HOSTNAME=${ORACLE_HOSTNAME} \
    UNIX_GROUP_NAME=oinstall \
    INVENTORY_LOCATION=${ORA_INVENTORY} \
    SELECTED_LANGUAGES=en,en_GB \
    ORACLE_HOME=${ORACLE_HOME} \
    ORACLE_BASE=${ORACLE_BASE} \
    oracle.install.db.InstallEdition=EE \
    oracle.install.db.DBA_GROUP=dba \
    oracle.install.db.OPER_GROUP=dba \
    oracle.install.db.BACKUPDBA_GROUP=dba \
    oracle.install.db.DGDBA_GROUP=dba \
    oracle.install.db.KMDBA_GROUP=dba \
    SECURITY_UPDATES_VIA_MYORACLESUPPORT=false \
    DECLINE_SECURITY_UPDATES=true

    

 ./runInstaller -silent -responseFile /home/oracle/database/db_install.rsp



 ==db_install.rsp

 gdbName=silent
sid=silent
databaseConfigType=SI
createAsContainerDatabase=false
templateName=General_Purpose.dbc
sysPassword=oracle12c
systemPassword=oracle12c
emConfiguration=NONE
datafileDestination=/u01/oradata
recoveryAreaDestination=/u01/recovery_area
storageType=FS
characterSet=AL32UTF8
sampleSchema=TRUE



dbca -silent -createDatabase -responseFile dbca.rsp

https://houseofbrick.com/blog/oracle-12-2-0-1-silent-installation/



